config/routes.rb
Sqli::Application.routes.draw do
  get "home/index"
  root :to => 'home#index'

  match "home/update_condition_options", :controller => 'home', :action => 'update_condition_options', :via => 'post', :as => 'home_update_condition_options'

  # Create tests
  match "create_test/class_new/:method(/:amount)", :controller => 'create_test', :action => 'class_new', :via => 'get', :as => 'create_test_class_new'
  match "create_test/class_create/:method(/:amount)", :controller => 'create_test', :action => 'class_create', :via => 'post', :as => 'create_test_class_create'
  match "create_test/relation_new/:method(/:amount)", :controller => 'create_test', :action => 'relation_new', :via => 'get', :as => 'create_test_relation_new'
  match "create_test/relation_create/:method(/:amount)", :controller => 'create_test', :action => 'relation_create', :via => 'post', :as => 'create_test_relation_create'

  # Read tests
  match "read_test/relation_objects_form/:method(/:option)", :controller => 'read_test', :action => 'relation_objects_form', :via => 'get', :as => 'read_test_relation_objects_form'
  match "read_test/relation_objects_perform/:method(/:option)", :controller => 'read_test', :action => 'relation_objects_perform', :via => 'post', :as => 'read_test_relation_objects_perform'
  match "read_test/relation_value_form/:method(/:option)", :controller => 'read_test', :action => 'relation_value_form', :via => 'get', :as => 'read_test_relation_value_form'
  match "read_test/relation_value_perform/:method(/:option)", :controller => 'read_test', :action => 'relation_value_perform', :via => 'post', :as => 'read_test_relation_value_perform'
  match "read_test/relation_by_sql_form/:method(/:option)", :controller => 'read_test', :action => 'relation_by_sql_form', :via => 'get', :as => 'read_test_relation_by_sql_form'
  match "read_test/relation_by_sql_perform/:method(/:option)", :controller => 'read_test', :action => 'relation_by_sql_perform', :via => 'post', :as => 'read_test_relation_by_sql_perform'
  match "read_test/relation_condition_option_form/:apply_method/:argument_type(/:argument_type_option)", :controller => 'read_test', :action => 'relation_condition_option_form', :via => 'get', :as => 'read_test_relation_condition_option_form'
  match "read_test/relation_condition_option_perform/:apply_method/:argument_type(/:argument_type_option)", :controller => 'read_test', :action => 'relation_condition_option_perform', :via => 'post', :as => 'read_test_relation_condition_option_perform'

  # Update tests
  match "update_test/relation_edit/:method/:option", :controller => 'update_test', :action => 'relation_edit', :via => 'get', :as => 'update_test_relation_edit'
  match "update_test/relation_update/:method/:option", :controller => 'update_test', :action => 'relation_update', :via => 'post', :as => 'update_test_relation_update'
  match "update_test/object_single_edit/:id/:method", :controller => 'update_test', :action => 'object_single_edit', :via => 'get', :as => 'update_test_object_single_edit'
  match "update_test/object_single_update/:id/:method", :controller => 'update_test', :action => 'object_single_update', :via => 'post', :as => 'update_test_object_single_update'
  match "update_test/object_multi_edit/:id/:method", :controller => 'update_test', :action => 'object_multi_edit', :via => 'get', :as => 'update_test_object_multi_edit'
  match "update_test/object_multi_update/:id/:method", :controller => 'update_test', :action => 'object_multi_update', :via => 'post', :as => 'update_test_object_multi_update'

  # Delete tests
  match "delete_test/relation_form/:method/:option", :controller => 'delete_test', :action => 'relation_form', :via => 'get', :as => 'delete_test_relation_form'
  match "delete_test/relation_perform/:method/:option", :controller => 'delete_test', :action => 'relation_perform', :via => 'post', :as => 'delete_test_relation_perform'
  match "delete_test/object_remove/:id/:method", :controller => 'delete_test', :action => 'object_remove', :via => 'get', :as => 'delete_test_object_remove'

  # Injection tests
  match "injection_test/injection_form/:method", :controller => 'injection_test', :action => 'injection_form', :via => 'get', :as => 'injection_test_injection_form'
  match "injection_test/injection_perform/:method", :controller => 'injection_test', :action => 'injection_perform', :via => 'post', :as => 'injection_test_injection_perform'

  # Catch all to disable logging of routing errors
  match '*path', :via => [:get, :post], :controller => 'application', :action => 'show_404'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  CONDITIONS_APPLY_METHODS = ["separated", "joined"]
  CONDITIONS_ARGUMENT_TYPES = ["string", "list", "array", "hash"]
  CONDITIONS_PLACEHOLDER_STYLES = ["question_mark", "named", "sprintf"]
  CONDITIONS_HASH_STYLES = ["equality", "range", "subset"]

  def index
    @objects = AllTypesObject.order(:id).limit(10)
    @amounts = 1..3
  end

  def update_condition_options
    File.open(CONDITION_OPTIONS_FILE, 'w') do |f|
      f.write(params[:apply_method] + "\n")
      f.write(params[:argument_type] + "\n")
      f.write(params[:placeholder_style] + "\n")
      f.write(params[:hash_style])
    end
    redirect_to home_index_path, :notice => 'Condition options updated successfully'
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def link_to_amounts(path, *args)
    s = ""
    @amounts.each do |amount|
      s += link_to amount, self.send(path, *args, amount)
      s += " "
    end
    s.html_safe
  end

  def link_to_objects(path, *args)
    s = ""
    @objects.each do |obj|
      s += link_to obj.id, self.send(path, obj, *args)
      s += " "
    end
    s.html_safe
  end
end

app/views/home/_condition_option_tests.html.erb
<% HomeController::CONDITIONS_APPLY_METHODS.each do |apply_method| %>
  <% HomeController::CONDITIONS_ARGUMENT_TYPES.each do |argument_type| %>
    <% if argument_type == "list" || argument_type == "array" %>
      <% argument_type_options = HomeController::CONDITIONS_PLACEHOLDER_STYLES %>
    <% elsif argument_type == "hash" %>
      <% argument_type_options = HomeController::CONDITIONS_HASH_STYLES %>
    <% end %>
    <% if argument_type_options.present? %>
      <% argument_type_options.each do |argument_type_option| %>
        <li><%= link_to "#{apply_method.humanize} #{argument_type.humanize} #{argument_type_option.humanize}", read_test_relation_condition_option_form_path(apply_method, argument_type, argument_type_option) %></li>
      <% end %>
    <% else %>
        <li><%= link_to "#{apply_method.humanize} #{argument_type.humanize}", read_test_relation_condition_option_form_path(apply_method, argument_type) %></li>
    <% end %>
  <% end %>
<% end %>

app/views/home/_condition_options.html.erb
<h2>Condition options</h2>
<% if running? %>
  <p>
    The condition options as currently set.<br />
    Set ApplicationController::RUN_MODE to false to change them.
  </p>
  <div>Apply method: <strong><%= @condition_options[:apply_method] %></strong></div>
  <div>Argument type: <strong><%= @condition_options[:argument_type] %></strong></div>
  <div>Placeholder style: <strong><%= @condition_options[:placeholder_style] %></strong></div>
  <div>Hash style: <strong><%= @condition_options[:hash_style] %></strong></div>
<% else %>
<%= form_tag(home_update_condition_options_path) do %>
  <p>
    The form below can be used to change the various condition options (apply_method, argument_type, placeholder_style, hash_style).<br />
    Conditions (mostly applied using the where or having method) can be set in various ways.<br />
    The options below control these ways.<br />
    These settings are global. They will be used for all methods using conditions (where or having), except the condition option tests, which explicitely overwrite these options.<br />
    <div style="font-weight: bold; text-decoration: underline;">Note: make sure to disable the condition options form before running the tests. Do this by setting ApplicationController::RUN_MODE to true.</div>
  </p>
  <div class="field">
    <%= label_tag('apply_method') %><br />
    <%= select_tag('apply_method', options_for_select(HomeController::CONDITIONS_APPLY_METHODS, :selected => @condition_options[:apply_method])) %>
     <div style="font-style: italic;">
      The apply method (separated/joined) determines whether the conditions should be applied seperately (using multiple where/having method calls) or joined in a large statement (using a single where/having method call).
    </div>
  </div>
  <div class="field">
    <%= label_tag('argument_type') %><br />
    <%= select_tag('argument_type', options_for_select(HomeController::CONDITIONS_ARGUMENT_TYPES, :selected => @condition_options[:argument_type])) %>
    <div style="font-style: italic;">
      The argument type (string/list/array/hash) determines whether the arguments should be applied as a string (one large statement string with values filled in), a list (statement string followed by a list with bind variables), an array (with a statement string and bind variables) or an hash.
    </div>
  </div>
  <div class="field">
    <%= label_tag('placeholder_style') %><br />
    <%= select_tag('placeholder_style', options_for_select(HomeController::CONDITIONS_PLACEHOLDER_STYLES, :selected => @condition_options[:placeholder_style])) %>
    <div style="font-style: italic;">
      The placeholder style (question_mark/named/sprintf) determines whether we want to use question mark (?) placeholders, named placeholders (:id) or sprintf type placeholders (%s).<br />
      This only has effect when the argument type is list or array.
    </div>
  </div>
  <div class="field">
    <%= label_tag('hash_style') %><br />
    <%= select_tag('hash_style', options_for_select(HomeController::CONDITIONS_HASH_STYLES, :selected => @condition_options[:hash_style])) %>
    <div style="font-style: italic;">
      The hash style (equality/range/subset) determines whether we want to create an equality condition, range condition (BETWEEN) or subset condition (IN).<br />
      This only has effect when the argument type is hash.
    </div>
  </div>
  <div class="actions">
    <%= submit_tag 'Submit' %>
  </div>
<% end %>
<% end %>

app/views/home/_tests.html.erb
<h2>Tests</h2>
<p>
  Below you can find the several tests/framework functionality included in this module:
<p>

<% if active_modules.include?('create') %>
<h3>Create tests enabled</h3>
<ul>
  <li>Class methods:
    <ul>
      <li><%= link_to 'Create', create_test_class_new_path('create') %></li>
      <li><%= link_to 'Create!', create_test_class_new_path('create!') %></li>
      <li>Create array: <%= link_to_amounts 'create_test_class_new_path', 'create_array' %></li>
      <li>Create! array: <%= link_to_amounts 'create_test_class_new_path', 'create!_array' %></li>
      <li><%= link_to 'Save', create_test_class_new_path('save') %></li>
      <li><%= link_to 'Save!', create_test_class_new_path('save!') %></li>
    </ul>
  </li>
  <li>Relation methods:
    <ul>
      <li><%= link_to 'Create', create_test_relation_new_path('create') %></li>
      <li><%= link_to 'Create!', create_test_relation_new_path('create!') %></li>
      <li>Create array: <%= link_to_amounts 'create_test_relation_new_path', 'create_array' %></li>
      <li>Create! array: <%= link_to_amounts 'create_test_relation_new_path', 'create!_array' %></li>
    </ul>
  </li>
</ul>
<p>Disable by removing 'create' from BENCHMARK_MODULES</p>
<% else %>
<h3>Create tests disabled</h3>
<p>Enable by adding 'create' to BENCHMARK_MODULES</p>
<% end %>

<% if active_modules.include?('read') %>
<h3>Read tests enabled</h3>
<ul>
  <li>Object finder relation methods:
    <ul>
      <li><%= link_to 'To_a', read_test_relation_objects_form_path('to_a') %></li>
      <li><%= link_to 'All', read_test_relation_objects_form_path('all') %> (deprecated)</li>
      <li><%= link_to 'Load', read_test_relation_objects_form_path('load') %></li>
      <li><%= link_to 'Reload', read_test_relation_objects_form_path('reload') %></li>
      <li><%= link_to 'Select', read_test_relation_objects_form_path('select') %></li>
      <li><%= link_to 'First', read_test_relation_objects_form_path('first') %></li>
      <li><%= link_to 'First!', read_test_relation_objects_form_path('first!') %></li>
      <li><%= link_to 'Last', read_test_relation_objects_form_path('last') %></li>
      <li><%= link_to 'Last!', read_test_relation_objects_form_path('last!') %></li>
      <li><%= link_to 'Take', read_test_relation_objects_form_path('take') %></li>
      <li><%= link_to 'Take!', read_test_relation_objects_form_path('take!') %></li>
      <li>Find:
        <%= link_to 'sub method', read_test_relation_objects_form_path('find', 'sub_method') %> (deprecated)
        <%= link_to 'single id', read_test_relation_objects_form_path('find', 'single_id') %>
        <%= link_to 'id list', read_test_relation_objects_form_path('find', 'id_list') %>
        <%= link_to 'id array', read_test_relation_objects_form_path('find', 'id_array') %>
      </li>
      <li><%= link_to 'Find_by', read_test_relation_objects_form_path('find_by') %></li>
      <li><%= link_to 'Find_by!', read_test_relation_objects_form_path('find_by!') %></li>
      <li><%= link_to 'Find_or_initialize_by', read_test_relation_objects_form_path('find_or_initialize_by') %></li>
      <li><%= link_to 'Find_or_create_by', read_test_relation_objects_form_path('find_or_create_by') %></li>
      <li><%= link_to 'Find_or_create_by!', read_test_relation_objects_form_path('find_or_create_by!') %></li>
      <li><%= link_to 'Find_by_...', read_test_relation_objects_form_path('dynamic_find_by') %></li>
      <li><%= link_to 'Find_by_...!', read_test_relation_objects_form_path('dynamic_find_by!') %></li>
      <li><%= link_to 'Find_each', read_test_relation_objects_form_path('find_each') %></li>
      <li><%= link_to 'Find_in_batches', read_test_relation_objects_form_path('find_in_batches') %></li>
      <li><%= link_to 'First_or_initialize', read_test_relation_objects_form_path('first_or_initialize') %></li>
      <li><%= link_to 'First_or_create', read_test_relation_objects_form_path('first_or_create') %></li>
      <li><%= link_to 'First_or_create!', read_test_relation_objects_form_path('first_or_create!') %></li>
    </ul>
  </li>
  <li>Value relation methods:
    <ul>
      <li><%= link_to 'Any?', read_test_relation_value_form_path('any-') %></li>
      <li><%= link_to 'Blank?', read_test_relation_value_form_path('blank-') %></li>
      <li><%= link_to 'Empty?', read_test_relation_value_form_path('empty-') %></li>
      <li><%= link_to 'Many?', read_test_relation_value_form_path('many-') %></li>
      <li>Exists?:
        <%= link_to 'no arguments', read_test_relation_value_form_path('exists-') %>
        <%= link_to 'id', read_test_relation_value_form_path('exists-', 'id') %>
        <%= link_to 'conditions array', read_test_relation_value_form_path('exists-', 'conditions_array') %>
        <%= link_to 'conditions hash', read_test_relation_value_form_path('exists-', 'conditions_hash') %>
      </li>
      <li><%= link_to 'Size', read_test_relation_value_form_path('size') %></li>
      <li><%= link_to 'Explain', read_test_relation_value_form_path('explain') %></li>
      <li><%= link_to 'Inspect', read_test_relation_value_form_path('inspect') %></li>
    </ul>
  </li>
  <li>Count relation methods:
    <ul>
      <li><%= link_to 'Average', read_test_relation_value_form_path('average') %></li>
      <li><%= link_to 'Count', read_test_relation_value_form_path('count') %></li>
      <li><%= link_to 'Maximum', read_test_relation_value_form_path('maximum') %></li>
      <li><%= link_to 'Minimum', read_test_relation_value_form_path('minimum') %></li>
      <li><%= link_to 'Sum', read_test_relation_value_form_path('sum') %></li>
      <li><%= link_to 'Calculate', read_test_relation_value_form_path('calculate') %></li>
      <li><%= link_to 'Pluck', read_test_relation_value_form_path('pluck') %></li>
      <li><%= link_to 'Ids', read_test_relation_value_form_path('ids') %></li>
    </ul>
  </li>
  <li>By SQL relation methods:
    <ul>
      <li>Find_by_sql:
        <%= link_to 'string', read_test_relation_by_sql_form_path('find_by_sql', 'string') %>
        <%= link_to 'array', read_test_relation_by_sql_form_path('find_by_sql', 'array') %>
      </li>
      <li>Count_by_sql:
        <%= link_to 'string', read_test_relation_by_sql_form_path('count_by_sql', 'string') %>
        <%= link_to 'array', read_test_relation_by_sql_form_path('count_by_sql', 'array') %>
      </li>
    </ul>
  </li>
  <li>Condition option tests:
    <ul>
      <%= render 'condition_option_tests' %>
    </ul>
  </li>
</ul>
<p>Disable by removing 'read' from BENCHMARK_MODULES</p>
<% else %>
<h3>Read tests disabled</h3>
<p>Enable by adding 'read' to BENCHMARK_MODULES</p>
<% end %>

<% if active_modules.include?('update') %>
<h3>Update tests enabled</h3>
<ul>
  <li>Relation methods:
    <ul>
      <li>Update:
        <%= link_to 'Single', update_test_relation_edit_path('update', 'single') %>
        <%= link_to 'Multi', update_test_relation_edit_path('update', 'multi') %>
      </li>
      <li>Update all:
        <%= link_to 'String', update_test_relation_edit_path('update_all', 'string') %>
        <%= link_to 'Array', update_test_relation_edit_path('update_all', 'array') %>
        <%= link_to 'Hash', update_test_relation_edit_path('update_all', 'hash') %>
      </li>
    </ul>
  </li>
  <li>Object single update:
    <ul>
      <li>Update attribute: <%= link_to_objects('update_test_object_single_edit_path', 'update_attribute') %></li>
      <li>Update column: <%= link_to_objects('update_test_object_single_edit_path', 'update_column') %></li>
      <li>Increment!: <%= link_to_objects('update_test_object_single_edit_path', 'increment!') %></li>
      <li>Decrement!: <%= link_to_objects('update_test_object_single_edit_path', 'decrement!') %></li>
      <li>Toggle!: <%= link_to_objects('update_test_object_single_edit_path', 'toggle!') %></li>
      <li>Touch: <%= link_to_objects('update_test_object_single_edit_path', 'touch') %></li>
      <li>Save: <%= link_to_objects('update_test_object_single_edit_path', 'save') %></li>
      <li>Save!: <%= link_to_objects('update_test_object_single_edit_path', 'save!') %></li>
    </ul>
  </li>
  <li>Object multiple updates:
    <ul>
      <li>Update: <%= link_to_objects('update_test_object_multi_edit_path', 'update') %></li>
      <li>Update!: <%= link_to_objects('update_test_object_multi_edit_path', 'update!') %></li>
      <li>Update attributes: <%= link_to_objects('update_test_object_multi_edit_path', 'update_attributes') %></li>
      <li>Update attributes!: <%= link_to_objects('update_test_object_multi_edit_path', 'update_attributes!') %></li>
      <li>Update columns: <%= link_to_objects('update_test_object_multi_edit_path', 'update_columns') %></li>
      <li>Save: <%= link_to_objects('update_test_object_multi_edit_path', 'save') %></li>
      <li>Save!: <%= link_to_objects('update_test_object_multi_edit_path', 'save!') %></li>
    </ul>
  </li>
</ul>
<p>Disable by removing 'update' from BENCHMARK_MODULES</p>
<% else %>
<h3>Update tests disabled</h3>
<p>Enable by adding 'update' to BENCHMARK_MODULES</p>
<% end %>

<% if active_modules.include?('delete') %>
<h3>Delete tests enabled</h3>
<ul>
  <li>Relation methods:
    <ul>
      <li>Delete:
        <%= link_to 'Single', delete_test_relation_form_path('delete', 'single') %>
        <%= link_to 'Multi', delete_test_relation_form_path('delete', 'multi') %>
      </li>
      <li>Destroy:
        <%= link_to 'Single', delete_test_relation_form_path('destroy', 'single') %>
        <%= link_to 'Multi', delete_test_relation_form_path('destroy', 'multi') %>
      </li>
      <li>Delete all:
        <%= link_to 'String', delete_test_relation_form_path('delete_all', 'string') %>
        <%= link_to 'Array', delete_test_relation_form_path('delete_all', 'array') %>
        <%= link_to 'Hash', delete_test_relation_form_path('delete_all', 'hash') %>
      </li>
      <li>Destroy all:
        <%= link_to 'String', delete_test_relation_form_path('destroy_all', 'string') %>
        <%= link_to 'Array', delete_test_relation_form_path('destroy_all', 'array') %>
        <%= link_to 'Hash', delete_test_relation_form_path('destroy_all', 'hash') %>
      </li>
    </ul>
  </li>
  <li>Object remove:
    <ul>
      <li>Delete: <%= link_to_objects('delete_test_object_remove_path', 'delete') %></li>
      <li>Destroy: <%= link_to_objects('delete_test_object_remove_path', 'destroy') %></li>
      <li>Destroy!: <%= link_to_objects('delete_test_object_remove_path', 'destroy!') %></li>
    </ul>
  </li>
</ul>
<p>Disable by removing 'delete' from BENCHMARK_MODULES</p>
<% else %>
<h3>Delete tests disabled</h3>
<p>Enable by adding 'delete' to BENCHMARK_MODULES</p>
<% end %>

<% if active_modules.include?('injection') %>
<h3>Injection tests enabled</h3>
<ul>
  <li><%= link_to 'Order', injection_test_injection_form_path('order') %></li>
  <li><%= link_to 'Where', injection_test_injection_form_path('where') %></li>
</ul>
<p>Disable by removing 'injection' from BENCHMARK_MODULES</p>
<% else %>
<h3>Injection tests disabled</h3>
<p>Enable by adding 'injection' to BENCHMARK_MODULES</p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to the SQL injection benchmark module</h1>
<p>
  This module is part of the Ruby on Rails security benchmark, which is a part of my Master Thesis research.<br />
  It is basically a <%= link_to 'Ruby on Rails', 'http://www.rubyonrails.org/', :target => '_blank' %> 3.2.14 web application aimed at covering all the SQL injection related functionality, which in the case of Rails is the <%= link_to 'ActiveRecord', 'http://api.rubyonrails.org/classes/ActiveRecord/Base.html', :target => '_blank' %> database interface, which handles all SQL query generation and execution.<br />
  It is not the intention to test this functionality by hand, but rather to use a automatic security analysis tool, such as the dynamic web vulnerability scanners <%= link_to 'Arachni', 'http://www.arachni-scanner.com/', :target => '_blank' %> and <%= link_to 'W3af', 'http://w3af.org/', :target => '_blank' %>. Since these scanners cannot scan the Rails framework directly, they need some kind of interface/bridge. That is what this benchmark application is meant for.<br />
  If these scanners find a security vulnerability in this application, this could very well mean there is a security vulnerability in the Rails framework itself. This is because this application uses the functionality provided by the Rails framework in the most basic way possible (thus likely not introducing a security vulnerability itself). Furthermore, it uses functionality that should be secure to use with input from untrusted source (according to the Rails API/documentation).<br />
  This benchmark module tends to be as complete as possible (using all the provided ActiveRecord functionality in all the ways possible). However, this is not always complete feasible. Therefore, some things might have been left out (for example all methods/options that are <%= link_to 'deprecated in rails 4', 'http://guides.rubyonrails.org/4_0_release_notes.html#active-record-deprecations', :target => '_blank' %> are left out). Please refer to my thesis (TODO link?) for more information.<br />
</p>

<%= render 'condition_options' %>

<%= render 'tests' %>